<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZRYh9Kr\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZRYh9Kr/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZRYh9Kr.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZRYh9Kr\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZRYh9Kr\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZRYh9Kr',
    'container.build_id' => '7aab3fcf',
    'container.build_time' => 1517942548,
));
